# TODO explain why constant
GRUB_IMAGE_COMPRESSION='xz'
GRUB_DIRECTORY='/usr/lib/grub'
GRUB_IMAGE_ROOT='boot'

GRUB_BIOS="${GRUB_DIRECTORY}/i386-pc"
GRUB_IMAGE_DIRECTORY="${GRUB_IMAGE_ROOT}/grub"
GRUB_IMAGE_ARCHIVE="${GRUB_IMAGE_ROOT}.tar"

GRUB_BIOS_SETUP="${GRUB_BIOS}/grub-bios-setup"
GRUB_IMAGE_FILE="${GRUB_IMAGE_DIRECTORY}/grub.cfg"
